---
driver:
   name: vagrant 
   customize:
     memory: 1024
   network:
     - ["private_network", {ip: "192.168.33.33"}]


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec


platforms:
- name: centos-6.7
  driver:
    box: bento/centos-6.7
    communicator: ssh
    username: vagrant
    password: vagrant


suites:
  - name: default
    run_list:
      - recipe[britomartis::default]
    attributes:
