---
driver:
   name: vagrant 
   customize:
     memory: 1024
   network:
     - ["private_network", {ip: "192.168.33.33"}]


#########################
# IN KITCHEN.LOCAL
#########################
#
# driver:
#   name: vra
#   verify_ssl: true/false
#   use_dns: true/false
#   tenant: vsphere.local
#   requested_for: email@example.com
#   server_ready_retries: xx
#   base_url: https://vraapp1.example.com
#   username: 
#   password: 


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec


platforms:
- name: centos-6.7
  driver:
    name: vagrant
    box: bento/centos-6.7
    communicator: ssh
    username: vagrant
    password: vagrant

- name: centos-6.7-vra
  driver:
    catalog_id: e529a05f-42f8-4dac-a7c5-637b5b9cd1bc
    subtenant_id: fd5d55f3-32a3-4d86-8b09-a75c58d79a82
    lease_days: 2
    request_timeout: 7200
    extra_parameters:
      provider-hostname:
        type: string
        value: 
      provider-Vrm.DataCenter.Location:
        type: string
        value: 

suites:
  - name: default
    run_list:
      - recipe[britomartis::default]
    attributes:
