---
driver:
   name: vagrant 
   customize:
     memory: 1024
   network:
     - ["private_network", {ip: "192.168.33.33"}]


#########################
# IN KITCHEN.LOCAL
#########################
#
# driver:
#   name: vra
#   verify_ssl: true/false
#   use_dns: true/false
#   tenant: vsphere.local
#   requested_for: hippo@example.com
#   server_ready_sleep_time: xx
#   server_ready_retries: xx
#   base_url: https://vraapp.example.com
#   username: hippo
#   password: p0tamus


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec


platforms:
- name: centos-6.7
  driver:
    name: vagrant
    box: bento/centos-6.7
    communicator: ssh
    username: vagrant
    password: vagrant
# - name: os-vra
#   driver:
#     catalog_id: 
#     subtenant_id: 
#     lease_days: 
#     request_timeout: 
#     extra_parameters:
#       provider-hostname:
#         type: string
#         value: 
#       provider-Vrm.DataCenter.Location:
#         type: string
#         value: 


suites:
  - name: default
    run_list:
      - recipe[britomartis::default]
    attributes:
