name 'britomartis'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures britomartis'
long_description 'Installs/Configures britomartis'
version '0.1.0'
