
source 'https://supermarket.chef.io'

metadata

group :ea do
	cookbook 'kris', path: '../kris'
	cookbook 'britomartis', path: '../britomartis'
end 

group :community do
	cookbook 'quick_start', '~> 0.7.0'
	cookbook 'git', '~> 4.3.4'
end 
