name             'kris'
maintainer       'Kristan Stewart'
maintainer_email 'kristan.stewart@gmail.com'
license          'All rights reserved'
description      'Installs/Configures kris'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 		 'chef-dk'
depends 		 'chef-server'
depends 		 'git', '~> 4.3'
depends 		 'jenkins'
depends 		 'java'